
name: Environment Variables List
on: 
    push:
         branches:
           - main
jobs:

  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions 
        run: ${{env.NPM_AUTH_TOKEN}}
      - name:  variables on Windows
        run: env.NPM_AUTH_TOKEN 