name: "🚀 release"

on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2
            - name: node
              uses: actions/setup-node@v3.2.0
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: adsblock-detector
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}